/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.simed.view;

import java.awt.Dimension;
import java.beans.PropertyVetoException;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;

/**
 *
 * @author Ranster
 */
public class JFramePrincipal extends javax.swing.JFrame {
   
    private static JFramePrincipal p;
    private static JIFrameCadastroEstados CadastroEstados;
    private static JIFrameCadastroCidade CadastroCidades;
    private static JIFrameCadastroBairros CadastroBairros;
   
      
    
    public JFramePrincipal() {
        initComponents();
        //jLabelDataAtual.setText(FormatarData.dataLonga());
        //Timer t = new Timer();
        //t.scheduleAtFixedRate(new Relogio(jLabelRelogio), 0, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuCadastroEstados = new javax.swing.JMenuItem();
        jMenuCadastrocidades = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JDesktopPanePrincipal.setOpaque(false);

        javax.swing.GroupLayout JDesktopPanePrincipalLayout = new javax.swing.GroupLayout(JDesktopPanePrincipal);
        JDesktopPanePrincipal.setLayout(JDesktopPanePrincipalLayout);
        JDesktopPanePrincipalLayout.setHorizontalGroup(
            JDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
        );
        JDesktopPanePrincipalLayout.setVerticalGroup(
            JDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 579, Short.MAX_VALUE)
        );

        jMenu3.setText("Sistema");

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Cadastros");

        jMenuCadastroEstados.setText("Cadastro de Estados");
        jMenuCadastroEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroEstadosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastroEstados);

        jMenuCadastrocidades.setText("Cadastro de Cidades");
        jMenuCadastrocidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrocidadesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastrocidades);

        jMenuItem1.setText("Cadastro de Bairros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Ajuda");

        jMenuItem3.setText("Sobre");
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDesktopPanePrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDesktopPanePrincipal)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuCadastroEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroEstadosActionPerformed
        if (CadastroEstados == null) {
            CadastroEstados = new JIFrameCadastroEstados();
            JDesktopPanePrincipal.add(CadastroEstados);
            CadastroEstados.setVisible(true);
            CadastroEstados.setPosicao();
        } else {
            try {
                CadastroEstados.setSelected(true);
            } catch (PropertyVetoException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_jMenuCadastroEstadosActionPerformed

    private void jMenuCadastrocidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrocidadesActionPerformed
         if (CadastroCidades == null) {
            CadastroCidades = new JIFrameCadastroCidade();
            JDesktopPanePrincipal.add(CadastroCidades);
            CadastroCidades.setVisible(true);
            CadastroCidades.setPosicao();
        } else {
            try {
                CadastroCidades.setSelected(true);
            } catch (PropertyVetoException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_jMenuCadastrocidadesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       if (CadastroBairros == null) {
            CadastroBairros = new JIFrameCadastroBairros();
            JDesktopPanePrincipal.add(CadastroBairros);
            CadastroBairros.setVisible(true);
            CadastroBairros.setPosicao();
        } else {
            try {
                CadastroBairros.setSelected(true);
            } catch (PropertyVetoException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    //Libera acesso ao Frame Principal
    public static JFramePrincipal getInstancia() {

        if (p == null) {
            p = new JFramePrincipal();
        }
        return p;
    }
     
    //Libera acesso ao JDESKTOPPANE através de outros JIFRAME do projeto
    public static JDesktopPane getDesktopPainel() {
        return getInstancia().JDesktopPanePrincipal;
    }
    
    //Informa ao JDesktopPane que a janela foi encerrada 
    public static void setTelaNull() {
        CadastroEstados = null;
        CadastroCidades = null;
        CadastroBairros = null;

    }
      
    /*
      //Adiciona a Label o Nome do Usuário Locado   
      public static void setLogado(Usuario usuario){
           getInstancia().jLabelUsuarioLogado.setText(usuario.getLogin());
      }
     
     //Retorna o nome do usuário Logado
      public static String getLogado(){
          return getInstancia().jLabelUsuarioLogado.getText();
      }      
     */
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDesktopPanePrincipal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadastroEstados;
    private javax.swing.JMenuItem jMenuCadastrocidades;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
