/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.simed.view;

import java.awt.Dimension;
import java.beans.PropertyVetoException;
import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author Ranster
 */
public class JFramePrincipal extends javax.swing.JFrame {
   
    private static JFramePrincipal p;
    private static JIFrameCadastroEstados CadastroEstados;
    private static JIFrameCadastroCidade CadastroCidades;
    private static JIFrameCadastroBairros CadastroBairros;
    private static JIFrameCadastroCep CadastroCep;
    private static JIFrameCadastroEmpresa CadastroEmpresa;
    private static JIFrameCadastroExame CadastroExame;
    private static JIFrameCadastroResultados CadastroResultados;
    private JMenuItem jMenuItemCadastroEmpresas;
    
   
      
    
    public JFramePrincipal() {
        initComponents();
        //jLabelDataAtual.setText(FormatarData.dataLonga());
        //Timer t = new Timer();
        //t.scheduleAtFixedRate(new Relogio(jLabelRelogio), 0, 1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JDesktopPanePrincipal = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuCadastroEstados = new javax.swing.JMenuItem();
        jMenuCadastrocidades = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuCadastroCep = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemCadastroEmpresas = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JDesktopPanePrincipal.setOpaque(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/simed/images/icons/if_Hospital_22911.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(558, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(218, 218, 218))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(jLabel1)
                .addContainerGap(363, Short.MAX_VALUE))
        );

        JDesktopPanePrincipal.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JDesktopPanePrincipalLayout = new javax.swing.GroupLayout(JDesktopPanePrincipal);
        JDesktopPanePrincipal.setLayout(JDesktopPanePrincipalLayout);
        JDesktopPanePrincipalLayout.setHorizontalGroup(
            JDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        JDesktopPanePrincipalLayout.setVerticalGroup(
            JDesktopPanePrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenu3.setText("Sistema");

        jMenuItem2.setText("Sair");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        jMenu1.setText("Cadastros");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });
        jMenu1.add(jSeparator1);

        jMenuCadastroEstados.setText("Cadastro de Estados");
        jMenuCadastroEstados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroEstadosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastroEstados);

        jMenuCadastrocidades.setText("Cadastro de Cidades");
        jMenuCadastrocidades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastrocidadesActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastrocidades);

        jMenuItem1.setText("Cadastro de Bairros");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuCadastroCep.setText("Cadastro de Cep");
        jMenuCadastroCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadastroCepActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuCadastroCep);
        jMenu1.add(jSeparator2);

        jMenu2.setText("Empresas");

        jMenuItemCadastroEmpresas.setText("Cadastro de Empresas");
        jMenuItemCadastroEmpresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroEmpresasActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemCadastroEmpresas);

        jMenu1.add(jMenu2);
        jMenu1.add(jSeparator3);

        jMenuItem5.setText("Cadastro de Exames");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuItem6.setText("Cadastro de Resultados");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu4.setText("Ajuda");

        jMenuItem3.setText("Sobre");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDesktopPanePrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JDesktopPanePrincipal, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuCadastroEstadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroEstadosActionPerformed
        if (CadastroEstados == null) {
            CadastroEstados = new JIFrameCadastroEstados();
            JDesktopPanePrincipal.add(CadastroEstados);
            CadastroEstados.setVisible(true);
            CadastroEstados.setPosicao();
        } else {
            try {
                CadastroEstados.setSelected(true);
            } catch (PropertyVetoException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_jMenuCadastroEstadosActionPerformed

    private void jMenuCadastrocidadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastrocidadesActionPerformed
         if (CadastroCidades == null) {
            CadastroCidades = new JIFrameCadastroCidade();
            JDesktopPanePrincipal.add(CadastroCidades);
            CadastroCidades.setVisible(true);
            CadastroCidades.setPosicao();
        } else {
            try {
                CadastroCidades.setSelected(true);
            } catch (PropertyVetoException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_jMenuCadastrocidadesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       if (CadastroBairros == null) {
            CadastroBairros = new JIFrameCadastroBairros();
            JDesktopPanePrincipal.add(CadastroBairros);
            CadastroBairros.setVisible(true);
            CadastroBairros.setPosicao();
        } else {
            try {
                CadastroBairros.setSelected(true);
            } catch (PropertyVetoException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuCadastroCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadastroCepActionPerformed
        if (CadastroCep == null) {
            CadastroCep = new JIFrameCadastroCep();
            JDesktopPanePrincipal.add(CadastroCep);
            CadastroCep.setVisible(true);
            CadastroCep.setPosicao();
        } else {
            try {
                CadastroEstados.setSelected(true);
            } catch (PropertyVetoException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_jMenuCadastroCepActionPerformed

    private void jMenuItemCadastroEmpresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroEmpresasActionPerformed
         if (CadastroEmpresa == null) {
            CadastroEmpresa = new JIFrameCadastroEmpresa();
            JDesktopPanePrincipal.add(CadastroEmpresa);
            CadastroEmpresa.setVisible(true);
            CadastroEmpresa.setPosicao();
        } else {
            try {
                CadastroEmpresa.setSelected(true);
            } catch (PropertyVetoException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_jMenuItemCadastroEmpresasActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        if (CadastroExame == null) {
            CadastroExame = new JIFrameCadastroExame();
            JDesktopPanePrincipal.add(CadastroExame);
            CadastroExame.setVisible(true);
            CadastroExame.setPosicao();
        } else {
            try {
                CadastroExame.setSelected(true);
            } catch (PropertyVetoException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
       if (CadastroResultados == null) {
            CadastroResultados = new JIFrameCadastroResultados();
            JDesktopPanePrincipal.add(CadastroResultados);
            CadastroResultados.setVisible(true);
            CadastroResultados.setPosicao();
        } else {
            try {
                CadastroResultados.setSelected(true);
            } catch (PropertyVetoException ex) {
                JOptionPane.showMessageDialog(this, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    //Libera acesso ao Frame Principal
    public static JFramePrincipal getInstancia() {

        if (p == null) {
            p = new JFramePrincipal();
        }
        return p;
    }
     
    //Libera acesso ao JDESKTOPPANE através de outros JIFRAME do projeto
    public static JDesktopPane getDesktopPainel() {
        return getInstancia().JDesktopPanePrincipal;
    }
    
    //Informa ao JDesktopPane que a janela foi encerrada 
    public static void setTelaNull() {
        CadastroEstados = null;
        CadastroCidades = null;
        CadastroBairros = null;
        CadastroCep = null;
        CadastroExame = null;
        CadastroResultados = null;
        CadastroEmpresa = null;
        

    }
      
    /*
      //Adiciona a Label o Nome do Usuário Locado   
      public static void setLogado(Usuario usuario){
           getInstancia().jLabelUsuarioLogado.setText(usuario.getLogin());
      }
     
     //Retorna o nome do usuário Logado
      public static String getLogado(){
          return getInstancia().jLabelUsuarioLogado.getText();
      }      
     */
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane JDesktopPanePrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuCadastroCep;
    private javax.swing.JMenuItem jMenuCadastroEstados;
    private javax.swing.JMenuItem jMenuCadastrocidades;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
