/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.simed.view;

import br.com.simed.crud.CadastroEstados;
import br.com.simed.crud.CadastroExame;
import br.com.simed.model.Estado;
import br.com.simed.model.Exame;
import br.com.simed.model.Tabela;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Ranster
 */
public class JIFrameCadastroExame extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrameCadastroExames
     */
    public JIFrameCadastroExame() {
        initComponents();
        TabelaExamesCadastrados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jText_IdExame = new javax.swing.JTextField();
        jText_NomeExame = new javax.swing.JTextField();
        jButton_Ignorar = new javax.swing.JButton();
        jButton_Novo = new javax.swing.JButton();
        jButton_Salvar = new javax.swing.JButton();
        jButton_Excluir = new javax.swing.JButton();
        jText_Buscar_Nome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Exames_Cadastrados = new javax.swing.JTable();
        jButton_Sair = new javax.swing.JButton();

        setResizable(true);
        setTitle("Cadastro de Exame - SIMED");

        jLabel1.setText("ID Exame:");

        jLabel2.setText("Nome: ");

        jText_IdExame.setEnabled(false);

        jText_NomeExame.setEnabled(false);

        jButton_Ignorar.setText("Ignorar");
        jButton_Ignorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IgnorarActionPerformed(evt);
            }
        });

        jButton_Novo.setText("Novo");
        jButton_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NovoActionPerformed(evt);
            }
        });

        jButton_Salvar.setText("Salvar");
        jButton_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalvarActionPerformed(evt);
            }
        });

        jButton_Excluir.setText("Excluir");
        jButton_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExcluirActionPerformed(evt);
            }
        });

        jText_Buscar_Nome.setToolTipText("Busca Por Nome ...");
        jText_Buscar_Nome.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jText_Buscar_NomeCaretUpdate(evt);
            }
        });

        jTable_Exames_Cadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Exames_Cadastrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Exames_CadastradosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Exames_Cadastrados);

        jButton_Sair.setText("Sair");
        jButton_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jText_Buscar_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton_Sair))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton_Novo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Salvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Excluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_Ignorar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jText_IdExame, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jText_NomeExame, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jText_IdExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jText_NomeExame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jButton_Novo)
                    .addComponent(jButton_Salvar)
                    .addComponent(jButton_Excluir)
                    .addComponent(jButton_Ignorar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jText_Buscar_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton_Sair)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_IgnorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IgnorarActionPerformed
       limparCampos();
       jText_NomeExame.setEnabled(false);

    }//GEN-LAST:event_jButton_IgnorarActionPerformed

    private void jButton_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NovoActionPerformed
    novo();
    TabelaExamesCadastrados();
    }//GEN-LAST:event_jButton_NovoActionPerformed

    private void jButton_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalvarActionPerformed
       if(!(jText_IdExame.getText().isEmpty() | jText_NomeExame.getText().isEmpty())){
       atualizar();
       novo();
       }else{
       salvar();
       novo();
       jText_NomeExame.setEnabled(false);
       }
    }//GEN-LAST:event_jButton_SalvarActionPerformed

    private void jButton_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExcluirActionPerformed
    excluir();
    jText_NomeExame.setEnabled(false);

    }//GEN-LAST:event_jButton_ExcluirActionPerformed

    private void jTable_Exames_CadastradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Exames_CadastradosMouseClicked
        if(evt.getClickCount() == 2) {
            
            jText_NomeExame.setEnabled(true);
            int linha = jTable_Exames_Cadastrados.getSelectedRow();
            jText_IdExame.setText(String.valueOf(jTable_Exames_Cadastrados.getValueAt(linha, 0)));
            jText_NomeExame.setText(String.valueOf(jTable_Exames_Cadastrados.getValueAt(linha, 1)));
            
            
        }
    }//GEN-LAST:event_jTable_Exames_CadastradosMouseClicked

    private void jButton_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SairActionPerformed
        dispose();
        JFramePrincipal.setTelaNull();
    }//GEN-LAST:event_jButton_SairActionPerformed

    private void jText_Buscar_NomeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jText_Buscar_NomeCaretUpdate
TabelaExamesCadastrados();        
    }//GEN-LAST:event_jText_Buscar_NomeCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Excluir;
    private javax.swing.JButton jButton_Ignorar;
    private javax.swing.JButton jButton_Novo;
    private javax.swing.JButton jButton_Sair;
    private javax.swing.JButton jButton_Salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Exames_Cadastrados;
    private javax.swing.JTextField jText_Buscar_Nome;
    private javax.swing.JTextField jText_IdExame;
    private javax.swing.JTextField jText_NomeExame;
    // End of variables declaration//GEN-END:variables
 private void limparCampos() {
        jText_IdExame.setText("");
        jText_NomeExame.setText("");
        TabelaExamesCadastrados();
        

    }
 public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);

    }
    
    private void novo() {
        limparCampos();
        jText_NomeExame.setEnabled(true);
        TabelaExamesCadastrados();

    }
    private void salvar() {
        
        if(!(jText_NomeExame.getText().isEmpty())){
            Exame exame = new Exame();
            exame.setNomeExame(jText_NomeExame.getText().trim().toUpperCase());

            CadastroExame cadastrar = new CadastroExame();
            cadastrar.incluirExame(exame);
            novo();
        }else{
            JOptionPane.showMessageDialog(this, "Dados Inválidos");
        }
     }
    private void atualizar() {
        
        if(!(jText_IdExame.getText().isEmpty() | jText_NomeExame.getText().isEmpty())){
            Exame exame = new Exame();
            exame.setNomeExame(jText_NomeExame.getText().trim().toUpperCase());
            exame.setCodigoExame(Integer.valueOf(jText_IdExame.getText().trim()));
            
            CadastroExame atualizar = new CadastroExame();
            atualizar.atualizarExame(exame);
            novo();
        }else{
            JOptionPane.showMessageDialog(this, "Dados Inválidos");
        }
    }
    
    public void TabelaExamesCadastrados() {
        
        Exame exame = new Exame();
        CadastroExame cadastrados = new CadastroExame();
        exame.setNomeExame(jText_Buscar_Nome.getText().toUpperCase().trim());
        
        ArrayList dados = cadastrados.listarExames(exame);
        String[] colunas = new String[]{"ID", "NOME"};
        Tabela modelo = new Tabela(dados, colunas);
        jTable_Exames_Cadastrados.setModel(modelo);
        jTable_Exames_Cadastrados.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTable_Exames_Cadastrados.getColumnModel().getColumn(0).setResizable(false);
        jTable_Exames_Cadastrados.getColumnModel().getColumn(1).setPreferredWidth(290);
        jTable_Exames_Cadastrados.getColumnModel().getColumn(1).setResizable(false);
       // jTable_Exames_Cadastrados.getColumnModel().getColumn(2).setPreferredWidth(80);
       // jTable_Exames_Cadastrados.getColumnModel().getColumn(2).setResizable(false);
       
        jTable_Exames_Cadastrados.getTableHeader().setReorderingAllowed(false);
        jTable_Exames_Cadastrados.setAutoResizeMode(jTable_Exames_Cadastrados.AUTO_RESIZE_OFF);
        jTable_Exames_Cadastrados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
    private void excluir() {
        if (!(jText_IdExame.getText().isEmpty() && jText_NomeExame.getText().isEmpty())) {

            int opcao = JOptionPane.showConfirmDialog(this, "Deseja Realmente Excluir este Registro", "", JOptionPane.YES_NO_OPTION);
            boolean resposta;
            resposta = opcao == JOptionPane.YES_OPTION;
            if (resposta) {
                Exame exame = new Exame();
                exame.setCodigoExame(Integer.valueOf(jText_IdExame.getText().trim()));

                CadastroExame excluir = new CadastroExame();
                excluir.excluirExame(exame);
                limparCampos();
            }

        }else{
            JOptionPane.showMessageDialog(this, "Nenhum Registro Foi Selecionado ...");
        }
    }
     
}