/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.simed.view;

import br.com.simed.crud.CadastroBairro;
import br.com.simed.crud.CadastroCidade;
import br.com.simed.model.Bairro;
import br.com.simed.model.Cidade;
import br.com.simed.model.Estado;
import br.com.simed.model.Tabela;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Ranster
 */
public class JIFrameCadastroBairros extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrameCadastroBairros
     */
    public JIFrameCadastroBairros() {
        initComponents();
        TabelaBairroCadastrados();
       

    }
public void setPosicao() {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);

    }
 public void listarBairro(){
         
          CadastroBairro c = new CadastroBairro();
          c.listaCidade(CBCidade);
          
     } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jText_NomeBairro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CBCidade = new javax.swing.JComboBox<>();
        jButton_Ignorar = new javax.swing.JButton();
        jText_Buscar_Nome = new javax.swing.JTextField();
        jButton_Novo = new javax.swing.JButton();
        jButton_Salvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Bairros_Cadastrados = new javax.swing.JTable();
        jButton_Sair = new javax.swing.JButton();
        jButton_Excluir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jText_IdBairro = new javax.swing.JTextField();

        setTitle("Cadastro de Bairros - SIMED");

        jLabel1.setText("Nome: ");

        jLabel2.setText("Cidade:");

        jButton_Ignorar.setText("Ignorar");
        jButton_Ignorar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_IgnorarActionPerformed(evt);
            }
        });

        jText_Buscar_Nome.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jText_Buscar_NomeCaretUpdate(evt);
            }
        });

        jButton_Novo.setText("novo");
        jButton_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_NovoActionPerformed(evt);
            }
        });

        jButton_Salvar.setText("Salvar");
        jButton_Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SalvarActionPerformed(evt);
            }
        });

        jTable_Bairros_Cadastrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable_Bairros_Cadastrados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Bairros_CadastradosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Bairros_Cadastrados);

        jButton_Sair.setText("Sair");
        jButton_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SairActionPerformed(evt);
            }
        });

        jButton_Excluir.setText("Excluir");
        jButton_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ExcluirActionPerformed(evt);
            }
        });

        jLabel3.setText("ID Bairro: ");

        jText_IdBairro.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 493, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(18, 18, 18)
                                    .addComponent(CBCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton_Novo)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_Salvar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_Excluir)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton_Ignorar))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(18, 18, 18)
                                    .addComponent(jText_NomeBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jText_IdBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(166, 166, 166)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_Sair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jText_Buscar_Nome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jText_IdBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jText_NomeBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CBCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Novo)
                    .addComponent(jButton_Salvar)
                    .addComponent(jButton_Excluir)
                    .addComponent(jButton_Ignorar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jText_Buscar_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_Sair)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_IgnorarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_IgnorarActionPerformed
        limparCampos();
        jText_NomeBairro.setEnabled(false);
        CBCidade.setEnabled(false);
    }//GEN-LAST:event_jButton_IgnorarActionPerformed

    private void jText_Buscar_NomeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jText_Buscar_NomeCaretUpdate
        TabelaBairroCadastrados();
    }//GEN-LAST:event_jText_Buscar_NomeCaretUpdate

    private void jButton_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_NovoActionPerformed
        listarBairro();
        novo();
        TabelaBairroCadastrados();
        limparCampos();
    }//GEN-LAST:event_jButton_NovoActionPerformed

    private void jButton_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SalvarActionPerformed
       if(!(jText_IdBairro.getText().isEmpty() | jText_NomeBairro.getText().isEmpty()| CBCidade.getSelectedItem().toString().isEmpty())){
           atualizar();
           novo();
            TabelaBairroCadastrados();
        }else{
            salvar();
            novo();
            TabelaBairroCadastrados();
        }

    }//GEN-LAST:event_jButton_SalvarActionPerformed

    private void jTable_Bairros_CadastradosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Bairros_CadastradosMouseClicked
        if(evt.getClickCount() == 2) {

            int linha = jTable_Bairros_Cadastrados.getSelectedRow();
            jText_IdBairro.setText(String.valueOf(jTable_Bairros_Cadastrados.getValueAt(linha, 0)));
            jText_NomeBairro.setText(String.valueOf(jTable_Bairros_Cadastrados.getValueAt(linha, 1)));
            CBCidade.setSelectedItem(String.valueOf(jTable_Bairros_Cadastrados.getValueAt(linha, 2)));

            //  CBCidade.getSelectedItem().toString(jTable_Bairros_Cadastrados.getValueAt(linha, 1));

        }
    }//GEN-LAST:event_jTable_Bairros_CadastradosMouseClicked

    private void jButton_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SairActionPerformed
        dispose();
        JFramePrincipal.setTelaNull();
    }//GEN-LAST:event_jButton_SairActionPerformed

    private void jButton_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ExcluirActionPerformed
        excluir();
        TabelaBairroCadastrados();
    }//GEN-LAST:event_jButton_ExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CBCidade;
    private javax.swing.JButton jButton_Excluir;
    private javax.swing.JButton jButton_Ignorar;
    private javax.swing.JButton jButton_Novo;
    private javax.swing.JButton jButton_Sair;
    private javax.swing.JButton jButton_Salvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Bairros_Cadastrados;
    private javax.swing.JTextField jText_Buscar_Nome;
    private javax.swing.JTextField jText_IdBairro;
    private javax.swing.JTextField jText_NomeBairro;
    // End of variables declaration//GEN-END:variables

private void novo() {
        limparCampos();
        jText_NomeBairro.setEnabled(true);
        CBCidade.setEnabled(true);

    }

 private void limparCampos() {
      jText_NomeBairro.setText("");
      jText_IdBairro.setText("");
      CBCidade.setSelectedItem("");

       // jText_NomeBairro.setEditable(false);
        //CBCidade.setEditable(false);
        TabelaBairroCadastrados();

       
    }
   private void salvar() {
        
        if(!(jText_NomeBairro.getText().isEmpty() | CBCidade.getSelectedItem().toString().isEmpty())){
            Bairro bairro = new Bairro();
            
            bairro.setNomeBairro(jText_NomeBairro.getText().trim().toUpperCase());
            int codBairro = ((Cidade) CBCidade.getSelectedItem()).getCodigocidade();
            bairro.setCodigocidade(codBairro);
            System.out.println("aqui : "+ bairro.getNomeBairro());
            System.out.println("aqui : "+ bairro.getCodigocidade());
            CadastroBairro cadastrar = new CadastroBairro();
            cadastrar.IncluirBairro(bairro);
            novo();
        }else{
            JOptionPane.showMessageDialog(this, "Dados Inválidos");
        }
     

    }
  
 public void TabelaBairroCadastrados() {
        
        Bairro cidade = new Bairro();
        CadastroBairro cidades_cadastrados = new CadastroBairro();
        cidade.setNome(jText_Buscar_Nome.getText().toUpperCase().trim());
        
        ArrayList dados = cidades_cadastrados.listarBairro(cidade);
        String[] colunas = new String[]{"ID", "NOME", "CIDADE"};
        Tabela modelo = new Tabela(dados, colunas);
        jTable_Bairros_Cadastrados.setModel(modelo);
        jTable_Bairros_Cadastrados.getColumnModel().getColumn(0).setPreferredWidth(80);
        jTable_Bairros_Cadastrados.getColumnModel().getColumn(0).setResizable(false);
        jTable_Bairros_Cadastrados.getColumnModel().getColumn(1).setPreferredWidth(290);
        jTable_Bairros_Cadastrados.getColumnModel().getColumn(1).setResizable(false);
        jTable_Bairros_Cadastrados.getColumnModel().getColumn(2).setPreferredWidth(290);
        jTable_Bairros_Cadastrados.getColumnModel().getColumn(2).setResizable(false);
       
        jTable_Bairros_Cadastrados.getTableHeader().setReorderingAllowed(false);
        jTable_Bairros_Cadastrados.setAutoResizeMode(jTable_Bairros_Cadastrados.AUTO_RESIZE_OFF);
        jTable_Bairros_Cadastrados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
    private void excluir() {
        if (!(jText_NomeBairro.getText().isEmpty() && jText_IdBairro.getText().isEmpty())) {

            int opcao = JOptionPane.showConfirmDialog(this, "Deseja Realmente Excluir este Registro", "", JOptionPane.YES_NO_OPTION);
            boolean resposta;
            resposta = opcao == JOptionPane.YES_OPTION;
            if (resposta) {
                Bairro bairro = new Bairro();
                bairro.setCodigobairro(Integer.valueOf(jText_IdBairro.getText().trim()));

                CadastroBairro excluir = new CadastroBairro();
                excluir.excluirBairro(bairro);
                limparCampos();
            }

        }else{
            JOptionPane.showMessageDialog(this, "Nenhum Registro Foi Selecionado ...");
        }
    }
       private void atualizar() {
        
        if(!(jText_NomeBairro.getText().isEmpty() | CBCidade.getSelectedItem().toString().isEmpty())){
            Bairro bairro = new Bairro();
            bairro.setNomeBairro(jText_NomeBairro.getText().trim().toUpperCase());
            int codCidade = ((Cidade) CBCidade.getSelectedItem()).getCodigocidade();
            bairro.setCodigocidade(codCidade);
            bairro.setCodigobairro(Integer.valueOf(jText_IdBairro.getText().trim()));
            

            CadastroBairro atualizar = new CadastroBairro();
            atualizar.atualizarBairro(bairro);
            novo();
        }else{
            JOptionPane.showMessageDialog(this, "Dados Inválidos");
        }
    }
}
